apiVersion: v1
kind: Namespace
metadata:
  name: cf-workloads
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-kpack-watcher
  namespace: cf-system
  labels:
    app.kubernetes.io/name: capi-kpack-watcher
    app.kubernetes.io/instance: capi-kpack-watcher-0
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: capi-kpack-watcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: capi-kpack-watcher
    spec:
      serviceAccountName: default
      containers:
        - name: capi-kpack-watcher
          image: localhost:5000/capi-kpack-watcher
          env:
          - name: CAPI_HOST
            value: capi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kpack-watcher
rules:
- apiGroups: ["build.pivotal.io"]
  resources: ["images", "builds", "builds/status", "images/status"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpack-watcher-binding
subjects:
- kind: ServiceAccount
  namespace: cf-system
  name: default
roleRef:
  kind: ClusterRole
  name: kpack-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kpack-watcher-pod-logs-reader
  namespace: cf-workloads
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kpack-watcher-pod-logs-binding
  namespace: cf-workloads
subjects:
- kind: ServiceAccount
  namespace: cf-system
  name: default
roleRef:
  kind: Role
  name: kpack-watcher-pod-logs-reader
  apiGroup: rbac.authorization.k8s.io
